// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";

const SUPABASE_URL = "https://pdmujwayibbxubxeexri.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_zo6jfsw8n2wru0NEj8LWJg_Pbq0J_3j";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
