import { useState, type FormEvent } from "react";
import { ArrowLeft, Plus, Save, Trash2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/auth/AuthContext";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { createSurvey } from "@/services/surveyService";
import type { QuestionDraft, QuestionType, SurveyDraft } from "@/types/models";

const blankQuestion = (): QuestionDraft => ({ type: "single_choice", title_ar: "", title_en: "", is_required: true, options: [{ label_ar: "", label_en: "" }, { label_ar: "", label_en: "" }] });
const choiceTypes: QuestionType[] = ["single_choice", "multiple_choice"];
const questionTypes: QuestionType[] = ["single_choice", "multiple_choice", "rating", "yes_no", "free_text"];
const typeKeys: Record<QuestionType, string> = { single_choice: "admin.singleChoice", multiple_choice: "admin.multipleChoice", rating: "admin.rating", yes_no: "admin.yesNo", free_text: "admin.freeText" };

export default function SurveyBuilderPage() {
  const { t } = useTranslation();
  const { session } = useAuth();
  const navigate = useNavigate();
  const [draft, setDraft] = useState<SurveyDraft>({ title_ar: "", title_en: "", description_ar: "", description_en: "", slug: "", response_policy: "open", questions: [blankQuestion()] });
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const updateQuestion = (index: number, update: Partial<QuestionDraft>) => setDraft((current) => ({ ...current, questions: current.questions.map((question, questionIndex) => questionIndex === index ? { ...question, ...update } : question) }));
  const updateOption = (questionIndex: number, optionIndex: number, field: "label_ar" | "label_en", value: string) => updateQuestion(questionIndex, { options: draft.questions[questionIndex].options.map((option, index) => index === optionIndex ? { ...option, [field]: value } : option) });
  const valid = draft.title_ar.trim() && draft.title_en.trim() && draft.slug.trim() && draft.questions.length > 0 && draft.questions.every((question) => question.title_ar.trim() && question.title_en.trim() && (!choiceTypes.includes(question.type) || (question.options.length >= 2 && question.options.every((option) => option.label_ar.trim() && option.label_en.trim()))));
  const handleSubmit = async (event: FormEvent) => { event.preventDefault(); setError(""); if (!valid || !session) { setError(t("admin.formInvalid")); return; } setSaving(true); try { await createSurvey(draft, session.user.id); navigate("/admin/surveys"); } catch { setError(t("common.error")); } finally { setSaving(false); } };

  return <form onSubmit={handleSubmit} className="mx-auto max-w-4xl space-y-6"><div className="flex items-center gap-3"><Button asChild variant="ghost" size="icon"><Link to="/admin/surveys" aria-label={t("common.back")}><ArrowLeft className="size-5 rtl:rotate-180" /></Link></Button><div><h2 className="text-2xl font-bold">{t("admin.newSurvey")}</h2><p className="text-sm text-muted-foreground">{t("admin.surveyIntro")}</p></div></div><Card><CardHeader><CardTitle>{t("admin.surveyManagement")}</CardTitle></CardHeader><CardContent className="grid gap-5 sm:grid-cols-2"><Field label={t("admin.surveyTitleAr")}><Input value={draft.title_ar} onChange={(e) => setDraft({ ...draft, title_ar: e.target.value })} dir="rtl" /></Field><Field label={t("admin.surveyTitleEn")}><Input value={draft.title_en} onChange={(e) => setDraft({ ...draft, title_en: e.target.value })} dir="ltr" /></Field><Field label={t("admin.surveyDescriptionAr")}><Textarea value={draft.description_ar} onChange={(e) => setDraft({ ...draft, description_ar: e.target.value })} dir="rtl" /></Field><Field label={t("admin.surveyDescriptionEn")}><Textarea value={draft.description_en} onChange={(e) => setDraft({ ...draft, description_en: e.target.value })} dir="ltr" /></Field><Field label={t("admin.slug")}><Input value={draft.slug} onChange={(e) => setDraft({ ...draft, slug: e.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "") })} dir="ltr" /></Field><Field label={t("admin.responsePolicy")}><select className="h-11 w-full rounded-lg border bg-card px-3" value={draft.response_policy} onChange={(e) => setDraft({ ...draft, response_policy: e.target.value as SurveyDraft["response_policy"] })}><option value="open">{t("survey.openParticipation")}</option><option value="one_per_employee">{t("survey.onePerEmployee")}</option></select></Field></CardContent></Card>
    <div className="flex items-center justify-between"><h3 className="text-xl font-bold">{t("admin.questions")}</h3><Button type="button" variant="outline" size="sm" onClick={() => setDraft({ ...draft, questions: [...draft.questions, blankQuestion()] })}><Plus className="size-4" />{t("admin.addQuestion")}</Button></div>
    {draft.questions.map((question, questionIndex) => <Card key={questionIndex}><CardHeader className="flex-row items-center justify-between"><CardTitle>{questionIndex + 1}</CardTitle>{draft.questions.length > 1 && <Button type="button" variant="ghost" size="icon" aria-label={t("admin.remove")} onClick={() => setDraft({ ...draft, questions: draft.questions.filter((_, index) => index !== questionIndex) })}><Trash2 className="size-4 text-destructive" /></Button>}</CardHeader><CardContent className="space-y-5"><div className="grid gap-5 sm:grid-cols-2"><Field label={t("admin.questionAr")}><Input value={question.title_ar} onChange={(e) => updateQuestion(questionIndex, { title_ar: e.target.value })} dir="rtl" /></Field><Field label={t("admin.questionEn")}><Input value={question.title_en} onChange={(e) => updateQuestion(questionIndex, { title_en: e.target.value })} dir="ltr" /></Field><Field label={t("admin.questionType")}><select className="h-11 w-full rounded-lg border bg-card px-3" value={question.type} onChange={(e) => updateQuestion(questionIndex, { type: e.target.value as QuestionType })}>{questionTypes.map((type) => <option value={type} key={type}>{t(typeKeys[type])}</option>)}</select></Field><label className="flex items-center gap-3 self-end rounded-lg border p-3 text-sm font-semibold"><input type="checkbox" checked={question.is_required} onChange={(e) => updateQuestion(questionIndex, { is_required: e.target.checked })} className="size-4 accent-[hsl(var(--primary))]" />{t("common.required")}</label></div>
      {choiceTypes.includes(question.type) && <div className="space-y-3"><Label>{t("admin.options")}</Label>{question.options.map((option, optionIndex) => <div key={optionIndex} className="grid grid-cols-[1fr_1fr_auto] gap-2"><Input value={option.label_ar} onChange={(e) => updateOption(questionIndex, optionIndex, "label_ar", e.target.value)} placeholder={t("admin.optionAr")} dir="rtl" /><Input value={option.label_en} onChange={(e) => updateOption(questionIndex, optionIndex, "label_en", e.target.value)} placeholder={t("admin.optionEn")} dir="ltr" /><Button type="button" variant="ghost" size="icon" aria-label={t("admin.remove")} disabled={question.options.length <= 2} onClick={() => updateQuestion(questionIndex, { options: question.options.filter((_, index) => index !== optionIndex) })}><Trash2 className="size-4" /></Button></div>)}<Button type="button" variant="outline" size="sm" onClick={() => updateQuestion(questionIndex, { options: [...question.options, { label_ar: "", label_en: "" }] })}><Plus className="size-4" />{t("admin.addOption")}</Button></div>}
    </CardContent></Card>)}
    {error && <p role="alert" className="rounded-lg bg-destructive/10 p-3 text-sm text-destructive">{error}</p>}<div className="safe-bottom flex justify-end"><Button type="submit" size="lg" disabled={saving}><Save className="size-4" />{saving ? t("admin.creatingSurvey") : t("admin.createSurvey")}</Button></div>
  </form>;
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
